# Generated by Django 6.0.1 on 2026-02-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluguer',
            options={'verbose_name': 'Aluguer', 'verbose_name_plural': 'Alugueres'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='itemaluguer',
            options={'verbose_name': 'Item do Aluguer', 'verbose_name_plural': 'Itens do Aluguer'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AddField(
            model_name='aluguer',
            name='uso_interno',
            field=models.BooleanField(default=False, verbose_name='Uso Interno / Empresa'),
        ),
    ]
